課題1.2
7coco/web_search_engine pull request #2
Opened 2017-03-27 09:28 UTC by 7coco

# 概要
なんとか動くようにはなりましたが、見通しが悪すぎて死にそうです。
うまくメソッドに切り出せばいいのでしょうか。
それともロジック自体却下？

# 入出力
```
/web_search_engine ❯❯❯ java FileSearch2 入力 README.md FileSearch1.java
入力された文字列が現れた行番号は以下の通りです。
README.mdの2行目 66文字目
21行目 80文字目
FileSearch1.javaの12行目 52文字目
22行目 25文字目
```

2017-03-27 09:56 UTC, kurodashota-mf requested changes
口頭でも伝えましたが、課題1.1からなるべく最小限の変更となるように修正しましょう！

2017-03-27 09:56 UTC, kurodashota-mf commented on FileSearch2.java
> +			Map<String, Map<Integer, List<Integer>>> result = search(args[0], fileNames);
searchメソッドは課題1.1から変えず、ファイルごとに呼び出すようにしてください。

2017-03-27 09:56 UTC, kurodashota-mf commented on FileSearch2.java
> +				String answer = createOutputStr(result);
ファイル名を渡すようにして結果文字列にファイル名を含めるようにしましょう

2017-03-27 09:56 UTC, kurodashota-mf commented on FileSearch2.java
> +	 * @param commandLineArgs
パラメータの説明をつけてください

2017-03-27 09:56 UTC, kurodashota-mf commented on FileSearch2.java
> +		for (int i = 0; i < commandLineArgs.length; i++) {
i=1から始めると、continueいらないです。

2017-03-27 09:56 UTC, kurodashota-mf commented on FileSearch2.java
> +		for (int i = 0; i < commandLineArgs.length; i++) {
更にいうと、
Arrays.copyOfRangeというメソッドを使えばcreateFileNamesList()は不要です。

2017-03-27 09:56 UTC, kurodashota-mf commented on FileSearch2.java
> +public class FileSearch2 {
ファイル名をフィールドに持つクラスを作成し、そのクラスにsearchメソッドとcreateOutputStrメソッドをもたせましょう。コンストラクタでファイル名を受け取るようにしてください。
伝わりづらいと思うので、わからなかったら聞きに来てください。

2017-03-27 09:56 UTC, kurodashota-mf commented on FileSearch2.java
> +public class FileSearch2 {
この修正は他の修正の後にやってください。

2017-03-28 01:08 UTC, kurodashota-mf commented on FileSearch2.java
> +public class FileSearch2 {
@7coco 
この修正に取り掛かる前に一回pushしてほしいです

2017-03-28 02:48 UTC, miyasumas requested changes
@7coco ↓これ対応してないので対応しましょう。
https://github.com/7coco/web_search_engine/pull/2/files#r108131048

2017-03-28 02:48 UTC, miyasumas commented on FileSearch2.java
> +	private static String createOutputStr(Map<String, Map<Integer, List<Integer>>> searchResultMap) {
これは全ファイルの検索結果、下のメソッド (`createStrBy`) は一ファイルごとの検索結果の文字列ができるはずなので、メソッド名も対になるように工夫してみましょう。(`searchInAllFiles` と `searchInFile` のような感じです。)
見る方もこれはセットで使われるということが気付きやすいです。

2017-03-28 04:58 UTC, miyasumas requested changes
@7coco コメントしました。

2017-03-28 04:58 UTC, miyasumas commented on FileSearcher.java
> +		fileName = f;
コンストラクタはこう書くことが多いです。
```
public FileSearcher(String fileName) {
    this.fileName = fileName;
}
```

2017-03-28 04:58 UTC, miyasumas commented on FileSearcher.java
> +	}
これは必要ないので無くていいです。

2017-03-28 04:58 UTC, miyasumas commented on FileSearcher.java
> +	private static String fileName;
`static` と付けてしまうとクラス変数となってしまいます。
このクラスをインスタンス化したとき、このフィールドはそれぞれのインスタンスで別々のものを持ちたいので、インスタンス変数にしておきましょう。

2017-03-28 05:19 UTC, miyasumas approved these changes
@7coco これでOKです。次に行きましょう。

2017-03-28 05:20 UTC, merged